import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Routes } from '@angular/router';
import { ProjectsComponent } from './projects/projects.component';
import { UsersComponent } from './users/users.component';
import { EditComponent } from './teams/edit/edit.component';


export const ManageRoutes: Routes = [
    {
        path: '',
        children: [
            {
                path: 'teams',
                component: 
            },
            {
                path: 'projects',
                component: ProjectsComponent,
            },
            {
                path: 'users',
                component: UsersComponent
            }
        ]
    }
];

@NgModule({
    imports: [
        CommonModule,
        RouterModule.forChild(ManageRoutes)
    ],
    declarations: [
        TeamsComponent,
        ProjectsComponent,
        UsersComponent,
        EditComponent,
        NewTeamComponent
    ]
})
export class ManageModule { }
