FROM node:10.15.3-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./yarn.lock package.json /usr/src/app/

RUN yarn install

COPY ./ /usr/src/app

# Build the Angular dashboard
RUN yarn ng build --prod

# Babel JavaScript Transcompile
RUN yarn server:build

ENV PORT 3000
EXPOSE 3000

CMD ["node", "dist/server"]